services:
  web:
    build:
      target: dev
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/anketa
    depends_on:
      - db

  db:
    # Hack: `-debian` because `mysql:8.0` uses oraclelinux 9, which requires x86-64-v2, but omega.svt cpu is too old.
    image: mysql:8.0-debian
    # The default plugin (caching_sha2_password) doesn't work with PHP < 7.4.
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anketa
      MYSQL_USER: anketa
      MYSQL_PASSWORD: anketa
      # This sets character_set_client when using the CLI ("docker compose exec db mysql ...").
      LANG: C.UTF-8
    volumes:
      - ./docker_mysql:/var/lib/mysql
