imports:
    - { resource: parameters.ini }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
    secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                path:     %kernel.root_dir%/../db/%database_file%

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    AnketaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    password: %mailer_password%
    
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

svt_libfajr:
    server: ais2.uniba.sk
    login:
        cosign_cookie: %ais_cookie%
        #cosign_proxy: /opt/cosign/proxy
    connection:
        curl:
            directory: /tmp
    trace: "null"
    
services:
    anketa.user_provider:
        class: AnketaBundle\Security\AnketaUserProvider
        arguments:
            - "@doctrine.orm.entity_manager"
            - ["@anketa.ais_user_source"]
    anketa.ais_retriever:
        class: AnketaBundle\Integration\AISRetriever
        arguments:
            - "@libfajr.trace"
            - "@libfajr.server.connection"
            - "@libfajr.login"
            - "@libfajr.window.main"
            - "@libfajr.window.factory.administracia_studia"
    anketa.ais_user_source:
        class: AnketaBundle\Security\AISUserSource
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@anketa.ais_retriever"
            - [["2010/2011", "Z"], ["2010/2011", "L"]] # brat iba tieto semestre
            - Yes # pouzit AIS ako zdroj opravneni?
    
security:
    factories:
        - "%kernel.root_dir%/../src/SVT/CosignBundle/Resources/config/security_factories.xml"
    providers:
        main:
            id: anketa.user_provider
    firewalls:
        main:
            pattern:    ^/.*
            cosign:     true
            anonymous:  true
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _zmen_usera }
            logout:
                path:     /logout
                target:   "https://login.uniba.sk/logout.cgi?https://anketa.fmph.uniba.sk/"
                handlers: [security.logout.handler.cosign]
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_HAS_VOTE]
        ROLE_AIS_STUDENT: [ROLE_STUDENT]
    access_control:
        - { path: /manage/.*, role: ROLE_ADMIN }
        - { path: /hlasuj/.*, role: ROLE_HAS_VOTE }
        - { path: /anketa/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
