imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AnketaBundle/Resources/config/services.yml }

parameters:
    other_instances:
        FMFI:
            url: https://anketa.fmph.uniba.sk/
            name: "Fakulta matematiky, fyziky a informatiky"
        PriF:
            url: https://anketa.uniba.sk/fns/
            name: "Prírodovedecká fakulta"
        FaF:
            url: https://anketa.uniba.sk/fpharm/
            name: "Farmaceutická fakulta"
    twig.exception_listener.class: AnketaBundle\EventListener\ExceptionListener

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:
        cookie_lifetime: 3600
        name:            anketasessid_%org_unit%_%anketa_instance%

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        # TODO: da sa nejako exportovat vsetky parametre?
        anketa_instance: %anketa_instance%
        skratka_fakulty: %skratka_fakulty%
        smernica_dekana: %smernica_dekana%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal: %database%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer: %mailer%

svt_libfajr:
    server: ais2.uniba.sk
    login: %libfajr_login%
    connection:
        curl:
            directory: %libfajr_cookie_path%
    trace: "null"

# TODO: co najviac z tohto niekam presunut (services.yml v AnketaBundle?)
services:
    anketa.user_provider:
        class: AnketaBundle\Security\AnketaUserProvider
        arguments:
            - "@doctrine.orm.entity_manager"
            - ["@anketa.ais_user_source"]
            #- ["@anketa.demo_user_source"]
            - ["@anketa.ldap_user_source"]
            #- ["@anketa.orgunit_demo_user_source"]
            # TODO nech je above zmenitelne
            - "@logger"
    anketa.ais_retriever:
        class: AnketaBundle\Integration\AISRetriever
        arguments:
            - "@libfajr.trace"
            - "@libfajr.server.connection"
            - "@libfajr.login"
            - "@libfajr.window.main"
            - "@libfajr.window.factory.administracia_studia"
    anketa.ais_user_source:
        class: AnketaBundle\Security\AISUserSource
        arguments:
            - "@database_connection"
            - "@doctrine.orm.entity_manager"
            - "@anketa.ais_retriever"
            - %ais_semestre%
            - %ais_brat_opravnenia%
            - "@anketa.subject_identification"
            - "@logger"
    anketa.ldap_retriever:
        class: AnketaBundle\Integration\LDAPRetriever
        arguments:
            - "ldaps://jas2.uniba.sk/,ldaps://jas1.uniba.sk/"
            - "dc=uniba,dc=sk"
    anketa.ldap_user_source:
        class: AnketaBundle\Security\LDAPUserSource
        arguments:
            - "@anketa.ldap_retriever"
            - "@logger"
    anketa.demo_user_source:
        class: AnketaBundle\Security\DemoUserSource
        arguments:
            - "@doctrine.orm.entity_manager"
    anketa.orgunit_demo_user_source:
        class: AnketaBundle\Security\OrgUnitDemoUserSource
        arguments:
            - [%org_unit%]
    anketa.subject_identification:
        class: AnketaBundle\Lib\SubjectIdentification
        # class: AnketaBundle\Lib\OldPriFSubjectIdentification # Pre PriF instanciu
