imports:
    - { resource: parameters.ini }

framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret: %csrf_secret%
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        lifetime:       3600
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                path:     %kernel.root_dir%/../db/%database_file%

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                mappings:
                    AnketaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    auth_mode: %mailer_auth_mode%
    password: %mailer_password%
    
jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
services:
    anketa.user_provider:
        class: AnketaBundle\Security\AnketaUserProvider
        arguments: [ "@doctrine.orm.entity_manager" ]
    
security:
    factories:
        - "%kernel.root_dir%/../src/SVT/CosignBundle/Resources/config/security_factories.xml"
    providers:
        main:
            id: anketa.user_provider
    firewalls:
        main:
            pattern:    /.*
            anonymous:  true
            cosign:     true
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: _zmen_usera }
            logout:
                path:     /logout
                target:   "https://login.uniba.sk/logout.cgi?https://anketa.fmph.uniba.sk/"
                handlers: [security.logout.handler.cosign]
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_HAS_VOTE]
    access_control:
        - { path: /manage/.*, role: ROLE_ADMIN }
        - { path: /hlasuj/.*, role: ROLE_HAS_VOTE }
        - { path: /anketa/.*, role: IS_AUTHENTICATED_FULLY }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
