_anketa:
    prefix:  /
    resource: "@AnketaBundle/Resources/config/routing.yml"

logout:
    pattern: /logout
    options: { i18n: false }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
