answer:
    pattern: /hlasuj/
    defaults: { _controller: AnketaBundle:Question:answerSubject, code: -1 }

answer_general:
    pattern: /hlasuj/vseobecne/{id}
    defaults: { _controller: AnketaBundle:Question:answerGeneral, id: -1 }
    requirements:
      id:  \d+

answer_subject:
    pattern: /hlasuj/predmet/{code}
    defaults: { _controller: AnketaBundle:Question:answerSubject, code: -1 }
