answer:
    pattern: /hlasuj/
    defaults: { _controller: AnketaBundle:Question:answerSubject, code: -1 }

answer_incomplete:
    pattern: /hlasuj/nevyplnene/
    defaults: { _controller: AnketaBundle:Question:answerIncomplete}

answer_general:
    pattern: /hlasuj/vseobecne/{id}
    defaults: { _controller: AnketaBundle:Question:answerGeneral, id: -1 }
    requirements:
      id:  \d+

answer_subject:
    pattern: /hlasuj/predmet/{code}
    defaults: { _controller: AnketaBundle:Question:answerSubject, code: -1 }

answer_subject_teacher:
    pattern: /hlasuj/predmet/{subject_code}/ucitel/{teacher_code}
    defaults: { _controller: AnketaBundle:Question:answerSubjectTeacher }


