_answer:
    pattern: /answer/
    defaults: { _controller: AnketaBundle:Answer:answerGeneral }

_answergeneral:
    pattern: /answer/general/
    defaults: { _controller: AnketaBundle:Answer:answerGeneral }
    