answer:
    pattern: /hlasuj/
    defaults: { _controller: AnketaBundle:Question:answerSubject, subject_slug: -1 }

answer_incomplete:
    pattern: /hlasuj/nevyplnene/
    defaults: { _controller: AnketaBundle:Question:answerIncomplete}

answer_general:
    pattern: /hlasuj/vseobecne/{id}
    defaults: { _controller: AnketaBundle:Question:answerGeneral, id: -1 }
    requirements:
      id:  \d+

answer_subject:
    pattern: /hlasuj/predmet/{subject_slug}
    defaults: { _controller: AnketaBundle:Question:answerSubject, subject_slug: -1 }

answer_subject_teacher:
    pattern: /hlasuj/predmet/{subject_slug}/ucitel/{teacher_code}
    defaults: { _controller: AnketaBundle:Question:answerSubjectTeacher }

answer_study_program:
    pattern: /hlasuj/program/{slug}
    defaults: { _controller: AnketaBundle:Question:answerStudyProgram, slug: -1 }

assoc_teacher_with_subject:
    pattern: /hlasuj/predmet/{subject_slug}/zmena-ucitela
    defaults: { _controller: AnketaBundle:TeachingAssociation:form }
    requirements:
      _method: GET

assoc_teacher_with_subject_process:
    pattern: /hlasuj/predmet/{subject_slug}/zmena-ucitela
    defaults: { _controller: AnketaBundle:TeachingAssociation:processForm }
    requirements:
      _method: POST