manage:
    pattern: /manage/
    defaults: { _controller: AnketaBundle:Manage:index }

#--------------------------
# Questions
#--------------------------

manage_questions:
    pattern: /manage/questions/
    defaults: { _controller: AnketaBundle:ManageQuestions:listQuestions }

list_questions:
    pattern: /manage/questions/list/
    defaults: { _controller: AnketaBundle:ManageQuestions:listQuestions }

add_question:
    pattern: /manage/questions/add/
    defaults: { _controller: AnketaBundle:ManageQuestions:addQuestion }

view_question:
    pattern: /manage/questions/{id}
    defaults: { _controller: AnketaBundle:ManageQuestions:viewQuestion }
    requirements:
      id:  \d+