report_study_programme:
    pattern: /reports/{season_slug}/studijny-program/{study_programme_slug}
    defaults: { _controller: AnketaBundle:Reports:studyProgramme, season_slug: null}
    requirements:
      study_programme_id:   \d+
report_department:
    pattern: /reports/{season_slug}/department/{department_id}
    defaults: { _controller: AnketaBundle:Reports:department, season_slug: null}
    requirements:
      department_id:   \d+
reports_my_reports:
    pattern: /reports/{season_slug}/my-reports
    defaults: { _controller: AnketaBundle:Reports:myReports, season_slug: null}