response:
    pattern: /vysledky/{season_slug}/moje-komentare
    defaults: { _controller: AnketaBundle:Response:listMine }
    requirements:
      season_slug:   "[a-z0-9-]+"

response_new:
    pattern: /odpovede/nova-odpoved/{section_slug}
    defaults: { _controller: AnketaBundle:Response:newResponse }
    requirements:
      section_slug:   ".+"
    
response_edit:
    pattern: /odpovede/{response_id}/uprav
    defaults: { _controller: AnketaBundle:Response:editResponse, delete: false }
    requirements:
      response_id:   \d+

response_delete:
    pattern: /odpovede/{response_id}/zmaz
    defaults: { _controller: AnketaBundle:Response:editResponse, delete: true }
    requirements:
      response_id:   \d+
