homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

# might be moved to separate routing file in case more managing areas are needed
_manage:
    pattern: /manage/
    resource: "@AnketaBundle/Resources/config/manage_routing.yml"

_anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Anketa:index }

_answerquestions:
    pattern: /answer/
    defaults: { _controller: AnketaBundle:Manage:answerQuestions }
_ping:
    pattern: /ping/{devName}
    defaults: { _controller: AnketaBundle:Ping:ping, devName: joe }