homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

login:
    pattern:  /login
    defaults: { _controller: AnketaBundle:Login:login }

faq:
    pattern:  /faq/
    defaults: { _controller: AnketaBundle:Welcome:faq }

anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Hlasovanie:index }

answer:
    pattern: /hlasuj/
    resource: "@AnketaBundle/Resources/config/answer_routing.yml"

reports:
    pattern: /reporty/
    resource: "@AnketaBundle/Resources/config/reports_routing.yml"

response:
    pattern: /odpovede/
    resource: "@AnketaBundle/Resources/config/response_routing.yml"

statistics:
    pattern: /vysledky/
    resource: "@AnketaBundle/Resources/config/statistics_routing.yml"

anonymizuj:
    pattern: /anonymizuj/
    defaults: { _controller: AnketaBundle:Anonymizacia:anonymizuj }

dakujeme:
    pattern: /dakujeme/
    defaults: { _controller: AnketaBundle:Anonymizacia:dakujeme }

api:
    pattern: /api/
    resource: "@AnketaBundle/Resources/config/api_routing.yml"

teacher_search:
    pattern: /ucitelia/vyhladavanie
    defaults: { _controller: AnketaBundle:Teacher:search }
    requirements:
      _method: GET  