homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

faq:
    pattern:  /faq/
    defaults: { _controller: AnketaBundle:Welcome:faq }

anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Hlasovanie:index }

manage:
    pattern: /manage/
    resource: "@AnketaBundle/Resources/config/manage_routing.yml"

answer:
    pattern: /hlasuj/
    resource: "@AnketaBundle/Resources/config/answer_routing.yml"

statistics:
    pattern: /vysledky/
    resource: "@AnketaBundle/Resources/config/statistics_routing.yml"

anonymizuj:
    pattern: /anonymizuj/
    defaults: { _controller: AnketaBundle:Anonymizacia:anonymizuj }

dakujeme:
    pattern: /dakujeme/
    defaults: { _controller: AnketaBundle:Anonymizacia:dakujeme }

ping:
    pattern: /ping/{devName}
    defaults: { _controller: AnketaBundle:Ping:ping, devName: -1 }
