homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

_anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Anketa:index }

_manage:
    pattern: /manage/
    resource: "@AnketaBundle/Resources/config/manage_routing.yml"

_answer:
    pattern: /answer/
    resource: "@AnketaBundle/Resources/config/answer_routing.yml"

_ping:
    pattern: /ping/{devName}
    defaults: { _controller: AnketaBundle:Ping:ping, devName: joe }