homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

login:
    pattern:  /login
    defaults: { _controller: AnketaBundle:Login:login }
    options: { i18n: false }

faq:
    pattern:  /faq/
    defaults: { _controller: AnketaBundle:Welcome:faq }

anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Question:answerIncomplete }

answer:
    prefix: /hlasuj/
    resource: "@AnketaBundle/Resources/config/answer_routing.yml"

reports:
    prefix: /reporty/
    resource: "@AnketaBundle/Resources/config/reports_routing.yml"

response:
    prefix: /odpovede/
    resource: "@AnketaBundle/Resources/config/response_routing.yml"

statistics:
    prefix: /vysledky/
    resource: "@AnketaBundle/Resources/config/statistics_routing.yml"

anonymizuj:
    pattern: /anonymizuj/
    defaults: { _controller: AnketaBundle:Anonymizacia:anonymizuj }

api:
    prefix: /api/
    resource: "@AnketaBundle/Resources/config/api_routing.yml"

teacher_search:
    pattern: /ucitelia/vyhladavanie
    defaults: { _controller: AnketaBundle:Teacher:search }
    requirements:
      _method: GET

admin_teaching_associations:
    pattern: /admin/ucitelia-priradenia
    defaults: { _controller: AnketaBundle:TeachingAssociationAdmin:index }
    requirements:
      _method: GET

admin_teaching_associations_process:
    pattern: /admin/ucitelia-priradenia
    defaults: { _controller: AnketaBundle:TeachingAssociationAdmin:processRequest }
    requirements:
      _method: POST

admin_comments_review:
    pattern: /admin/comments-review/{page}
    defaults: { _controller: AnketaBundle:CommentReviewAdmin:index, page: 0 }
    requirements:
      _method: GET
      page:  \d+

admin_comments_review_process:
    pattern: /admin/comments-review
    defaults: { _controller: AnketaBundle:CommentReviewAdmin:processRequest }
    requirements:
      _method: POST
