homepage:
    pattern:  /
    defaults: { _controller: AnketaBundle:Welcome:index }

anketa:
    pattern: /anketa/
    defaults: { _controller: AnketaBundle:Hlasovanie:index }

manage:
    pattern: /manage/
    resource: "@AnketaBundle/Resources/config/manage_routing.yml"

answer:
    pattern: /hlasuj/
    resource: "@AnketaBundle/Resources/config/answer_routing.yml"

ping:
    pattern: /ping/{devName}
    defaults: { _controller: AnketaBundle:Ping:ping, devName: -1 }
