
services:
    anketa.listener.preexecute:
        class: AnketaBundle\Extension\AnketaPreExecuteControllerExtension
        tags: [{ name: kernel.event_listener, event: kernel.controller, method: onKernelController }]
    anketa.twig.extension:
        class: AnketaBundle\Extension\AnketaTwigExtension
        tags: [{ name: twig.extension }]
        arguments: ["@service_container"]    # TODO :-(
    anketa.menu.hlasovanie:
        class: AnketaBundle\Menu\HlasovanieMenu
        arguments: ["@service_container"]    # TODO :-(
    anketa.menu.statistics:
        class: AnketaBundle\Menu\StatisticsMenu
        arguments: ["@service_container"]    # TODO :-(
    anketa.access.hlasovanie:
        class: AnketaBundle\Access\HlasovanieAccess
        arguments: ["@security.context", "@doctrine.orm.entity_manager", "%org_unit%"]
    anketa.access.statistics:
        class: AnketaBundle\Access\StatisticsAccess
        arguments: ["@security.context", "@doctrine.orm.entity_manager"]
    anketa.teacher_search:
        class: AnketaBundle\Integration\LDAPTeacherSearch
        arguments: ["@anketa.ldap_retriever", "%org_unit%"]
    anketa.subjects.action_listener:
        class: AnketaBundle\EventListener\SubjectImportListener
        arguments: ["@service_container", "%user_info_zdroje%"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
