statistics:
    pattern: /vysledky
    defaults: { _controller: AnketaBundle:Statistics:listGeneral, season_slug: null}

statistics_season:
    pattern: /vysledky/{season_slug}
    defaults: { _controller: AnketaBundle:Statistics:listGeneral}

statistics_list_subjects:
    pattern: /vysledky/{season_slug}/predmety/
    defaults: { _controller: AnketaBundle:Statistics:listSubjects}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_my_subjects:
    pattern: /vysledky/{season_slug}/moje-predmety
    defaults: { _controller: AnketaBundle:Statistics:listMySubjects }
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_programs:
    pattern: /vysledky/{season_slug}/programy
    defaults: { _controller: AnketaBundle:Statistics:listStudyPrograms}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_general:
    pattern: /vysledky/{season_slug}/vseobecne
    defaults: { _controller: AnketaBundle:Statistics:listGeneral}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_report:
    pattern: /flag/{answer_id}
    defaults: { _controller: AnketaBundle:Statistics:reportInappropriate}
    requirements:
      season_slug:   "[a-z0-9-]+"
      answer_id: \d+

statistics_results:
    pattern: /vysledky/{section_slug}
    defaults: { _controller: AnketaBundle:Statistics:results }
    requirements:
      section_slug: ".+"

