statistics:
    pattern: /vysledky
    defaults: { _controller: AnketaBundle:Statistics:general, season_slug: null}

statistics_subjects:
    pattern: /vysledky/{season_slug}/predmety/{category}
    defaults: { _controller: AnketaBundle:Statistics:subjects, category: null}
    requirements:
      season_slug:   "[a-z0-9-]+"
      category:      "[a-zA-Z0-9-]*"

results_subject:
    pattern: /vysledky/{season_slug}/predmet/{subject_code}
    defaults: { _controller: AnketaBundle:Statistics:resultsSubject}
    requirements:
      season_slug:   "[a-z0-9-]+"
      subject_code:  "[a-zA-Z0-9-]+"

results_subject_teacher:
    pattern: /vysledky/{season_slug}/predmet/{subject_code}/ucitel/{teacher_id}
    defaults: { _controller: AnketaBundle:Statistics:resultsSubjectTeacher}
    requirements:
      season_slug:   "[a-z0-9-]+"
      subject_code:  "[a-zA-Z0-9-]+"
      teacher_id:  \d+

statistics_general:
    pattern: /vysledky/{season_slug}/vseobecne
    defaults: { _controller: AnketaBundle:Statistics:general}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_results_general:
    pattern: /vysledky/{season_slug}/vseobecne/{question_id}
    defaults: { _controller: AnketaBundle:Statistics:resultsGeneral}
    requirements:
      season_slug:   "[a-z0-9-]+"
      question_id: \d+
