statistics:
    pattern: /vysledky
    defaults: { _controller: AnketaBundle:Statistics:general, season_slug: null}

statistics_season:
    pattern: /vysledky/{season_slug}
    defaults: { _controller: AnketaBundle:Statistics:general}

statistics_subjects:
    pattern: /vysledky/{season_slug}/predmety/{category}
    defaults: { _controller: AnketaBundle:Statistics:subjects, category: null}
    requirements:
      season_slug:   "[a-z0-9-]+"
      category:      "[a-zA-Z0-9-]*"

statistics_mySubjects:
    pattern: /vysledky/{season_slug}/moje-predmety
    defaults: { _controller: AnketaBundle:Statistics:mySubjects }
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_study_programs:
    pattern: /vysledky/{season_slug}/programy
    defaults: { _controller: AnketaBundle:Statistics:studyPrograms}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_general:
    pattern: /vysledky/{season_slug}/vseobecne
    defaults: { _controller: AnketaBundle:Statistics:general}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_report:
    pattern: /vysledky/{season_slug}/report/{answer_id}
    defaults: { _controller: AnketaBundle:Statistics:reportInappropriate}
    requirements:
      season_slug:   "[a-z0-9-]+"
      answer_id: \d+

statistics_results:
    pattern: /vysledky/{section_slug}
    defaults: { _controller: AnketaBundle:Statistics:results }
    requirements:
      section_slug: ".+"

