statistics:
    pattern: /vysledky
    defaults: { _controller: AnketaBundle:Statistics:seasonReport}

statistics_slash:
    pattern: /vysledky/
    defaults: { _controller: AnketaBundle:Statistics:seasonReport}

statistics_season:
    pattern: /vysledky/{season_slug}
    defaults: { _controller: AnketaBundle:Statistics:seasonReport}

statistics_list_subjects:
    pattern: /vysledky/{season_slug}/predmety/
    defaults: { _controller: AnketaBundle:Statistics:listSubjects}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_my_subjects:
    pattern: /vysledky/{season_slug}/moje-predmety
    defaults: { _controller: AnketaBundle:Statistics:listMySubjects }
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_programs:
    pattern: /vysledky/{season_slug}/programy
    defaults: { _controller: AnketaBundle:Statistics:listStudyPrograms}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_list_general:
    pattern: /vysledky/{season_slug}/vseobecne
    defaults: { _controller: AnketaBundle:Statistics:listGeneral}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_statement:
    pattern: /vysledky/{season_slug}/stanovisko
    defaults: { _controller: AnketaBundle:Statistics:officialStatement}
    requirements:
      season_slug:   "[a-z0-9-]+"

statistics_flag:
    pattern: /flag/{answer_id}
    defaults: { _controller: AnketaBundle:Statistics:flagInappropriate}
    requirements:
      answer_id: \d+

statistics_results:
    pattern: /vysledky/{section_slug}
    defaults: { _controller: AnketaBundle:Statistics:results }
    requirements:
      section_slug: ".+"

